package roadie

var languages = map[string]int{
	"english_us":           0x0,
	"english":              0x1,
	"english_gb":           0x1,
	"german":               0x2,
	"french":               0x3,
	"spanish":              0x4,
	"esperanto":            0x5,
	"ido":                  0x6,
	"russian":              0x7,
	"irish":                0x8,
	"maltese":              0x9,
	"tamil":                0x0A,
	"chuvash":              0x0B,
	"chinese_traditional":  0x0C,
	"serbian":              0x0D,
	"norwegian_nynorsk":    0x0E,
	"welsh":                0x0F,
	"belarusian":           0x10,
	"marathi":              0x11,
	"faroese":              0x12,
	"scottish_gaelic":      0x13,
	"arabic":               0x14,
	"czech":                0x15,
	"slovak":               0x16,
	"bulgarian":            0x18,
	"afrikaans":            0x1B,
	"greek":                0x1E,
	"dutch":                0x1F,
	"basque":               0x21,
	"catalan":              0x22,
	"luxembourgish":        0x23,
	"hungarian":            0x24,
	"macedonian":           0x26,
	"italian":              0x27,
	"romanian":             0x28,
	"icelandic":            0x29,
	"latvian":              0x2A,
	"lithuanian":           0x2B,
	"slovenian":            0x2C,
	"danish":               0x2D,
	"swedish":              0x2E,
	"norwegian_bokmal":     0x2F,
	"polish":               0x30,
	"galician":             0x31,
	"frisian":              0x32,
	"ukrainian":            0x33,
	"estonian":             0x34,
	"finnish":              0x35,
	"portuguese":           0x36,
	"brazilian_portuguese": 0x37,
	"croatian":             0x38,
	"japanese":             0x39,
	"korean":               0x3A,
	"malay":                0x3C,
	"english_au":           0x3D,
	"turkish":              0x3E,
	"thai":                 0x42,
	"vietnamese":           0x54,
	"mexican_spanish":      0x55,
	"chinese_simplified":   0x56,
	"indonesian":           0x5A,
	"urdu":                 0x5C,
	"hebrew":               0x61,
	"persian":              0x62,
	"latin":                0x66,
}

func GetLanguageId(language string) (value int) {
	if value, ok := languages[language]; ok {
		return value
	}

	return 1
}
